services:
  - type: web
    name: volantinomix
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    rootDir: backend